spring:
  application:
    name: lopez-dubbo-consumer
    
server:
  port: 9090
  
dubbo:
  application:
    name: ${spring.application.name}
    version: 1.0.0
  registry:
    address: zookeeper://127.0.0.1:2181
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache